name: iv_project_repository
description: "IV Project Repository"
version: 0.0.7
homepage:
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  # iv_project_model:
  #   path: ../iv_project_model

  iv_project_model:
    git:
      url: https://github.com/faequl96/iv_project_model.git
      ref: 0.0.4

  # iv_project_api:
  #   path: ../iv_project_api

  iv_project_api:
    git:
      url: git@github.com:faequl96/iv_project_api.git
      ref: 0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
